name: 개발서버 MySQL 배포

on:
  pull_request:
    branches:
      - "develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 연결 및 MySQL 이미지 실행
        uses: appleboy/ssh-action@master 
        with:
          username: ubuntu
          host: ${{ secrets.HOST_DEV }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker stop mysql-dev
            sudo docker rm mysql-dev
            sudo docker rmi mysql:9.0.1
            sudo docker pull mysql:9.0.1
            sudo docker run -d \
                --name mysql-dev \
                --network backend \
                -e MYSQL_DATABASE=${{ secrets.DATABASE_NAME_DEV }} \
                -e MYSQL_ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD_DEV }} \
                -e TZ=Asia/Seoul \
                -p 3306:3306 \
                -v ./mysql-data:/var/lib/mysql \
                mysql:9.0.1
